<#
.SYNOPSIS
  Runs the NEURAL AI reinforcement-learning loop (self-play -> train -> evaluate) for
  several generation-attempts in a row, unattended, logging progress to a timestamped
  log file. Includes a promotion gate: a newly trained checkpoint only becomes the new
  "best" (the base the next attempt self-plays and trains from) if it does not score
  worse against -Opponent than the current best did. This exists because an earlier,
  ungated version of this loop ran 40 generation-attempts straight while win rate against
  every opponent (including the weakest, DEFAULT) stayed flat at 0% -- worse than the
  untrained baseline checkpoint, which had scored 11% against DEFAULT. Without a gate,
  one bad training attempt permanently degrades every attempt after it, since self-play
  data generated by an already-bad policy stays bad.

  Start the YonmokuRessen server in another window before running this. For an
  unattended overnight run, set NEURAL_MCTS_SIMULATIONS back to something modest
  (e.g. 200-400) on the server so each evaluation game doesn't take too long.

  Run this from the repository root (YonmokuRessen-Neural-Network).

.EXAMPLE
  # checkpoints/model_rl_gen2.pt already exists; attempt 6 more generations (gen3..gen8),
  # gated against DEFAULT, keeping whichever checkpoint actually is not worse each time.
  .\scripts\run_rl_loop.ps1 -FromGen 2 -Generations 6

.EXAMPLE
  # Restart from an explicit checkpoint (e.g. the pre-RL imitation baseline) instead of
  # the gen-numbered default.
  .\scripts\run_rl_loop.ps1 -FromGen 2 -FromCheckpoint checkpoints/model_base.pt -Generations 10
#>

param(
    [Parameter(Mandatory = $true)]
    [int]$FromGen,
    [int]$Generations = 5,
    [int]$SelfplayGames = 60,
    [int]$SelfplaySimulations = 200,
    [int]$SelfplayConcurrency = 6,
    [int]$EvalGames = 10,
    [int]$EvalConcurrency = 4,
    [string]$Opponent = "DEFAULT",
    [string]$Server = "http://localhost:8080",
    [string]$PythonCpu = "..\.venv\Scripts\python.exe",
    [string]$PythonGpu = "..\.venv-rocm\Scripts\python.exe",
    # Train on ALL accumulated self-play data (a growing replay buffer), not just the
    # newest generation's file.
    [string]$DataGlob = "data/rl_selfplay_gen*.jsonl",
    # Override which checkpoint to start from (defaults to checkpoints/model_rl_gen{FromGen}.pt).
    [string]$FromCheckpoint = "",
    # Passed through to train_rl.py's --lr / --epochs. Lower/fewer than train_rl.py's own
    # defaults (1e-3 / 20) are worth trying if generations plateau even with a promotion
    # gate and a growing replay buffer -- a high learning rate can make each generation's
    # fine-tuning step too large/unstable to compound steadily.
    [double]$Lr = 0.001,
    [int]$TrainEpochs = 20,
    # Fraction (0-1) of each generation's self-play games to play against a built-in AI
    # (chosen from -VsBuiltinLevels) instead of pure network-vs-network self-play. Guards
    # against self-play collapse: training on nothing but self-play data can make the
    # network strong against copies of itself while losing the ability to handle a
    # qualitatively different opponent like DEFAULT (this is what was actually happening --
    # see README.md).
    [double]$VsBuiltinRatio = 0.0,
    [string]$VsBuiltinLevels = "DEFAULT,TEST,TEST2,TEST3"
)

$logFile = "training_log_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt"

function Write-Log {
    param([string]$Message)
    $line = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') $Message"
    Write-Host $line
    Add-Content -Path $logFile -Value $line -Encoding utf8
}

# Runs evaluate.py against a checkpoint and returns its win rate as a double (0-100),
# or -1 if the win rate could not be determined (evaluate.py failed or produced no
# parseable "win rate" line).
function Get-WinRate {
    param([string]$Checkpoint)

    $output = & $PythonCpu -m yonmoku_nn.evaluate --server $Server --opponent $Opponent --games $EvalGames `
        --random-opening-plies 4 --concurrency $EvalConcurrency --candidate $Checkpoint
    $exitCode = $LASTEXITCODE
    $output | ForEach-Object { Add-Content -Path $logFile -Value $_ -Encoding utf8 }

    if ($exitCode -ne 0) {
        Write-Log "WARNING: evaluate failed (exit $exitCode) while scoring $Checkpoint."
        return -1
    }
    $winRateLine = $output | Select-String "win rate:\s*([\d.]+)%" | Select-Object -First 1
    if (-not $winRateLine) {
        Write-Log "WARNING: could not find a win rate line while scoring $Checkpoint."
        return -1
    }
    return [double]$winRateLine.Matches[0].Groups[1].Value
}

Write-Log "=== RL loop start: from gen ${FromGen}, ${Generations} generation-attempt(s) requested, gated vs $Opponent ==="
Write-Log "selfplay: games=$SelfplayGames simulations=$SelfplaySimulations concurrency=$SelfplayConcurrency vs-builtin-ratio=$VsBuiltinRatio($VsBuiltinLevels) / train: lr=$Lr epochs=$TrainEpochs / eval: games=$EvalGames concurrency=$EvalConcurrency"

try {
    Invoke-WebRequest -Uri $Server -UseBasicParsing -TimeoutSec 5 | Out-Null
} catch {
    Write-Log "ERROR: cannot reach $Server. Start the YonmokuRessen server first. Aborting."
    exit 1
}

if ($FromCheckpoint -ne "") {
    $bestCheckpoint = $FromCheckpoint
} else {
    $bestCheckpoint = "checkpoints/model_rl_gen${FromGen}.pt"
}
if (-not (Test-Path $bestCheckpoint)) {
    Write-Log "ERROR: $bestCheckpoint not found. Aborting."
    exit 1
}

Write-Log "--- baseline: scoring the starting checkpoint ($bestCheckpoint) vs $Opponent ---"
$bestWinRate = Get-WinRate -Checkpoint $bestCheckpoint
if ($bestWinRate -lt 0) {
    Write-Log "ERROR: could not score the starting checkpoint. Aborting."
    exit 1
}
Write-Log "baseline win rate: $bestWinRate% ($bestCheckpoint)"

$gen = $FromGen
for ($i = 1; $i -le $Generations; $i++) {
    $gen = $gen + 1
    $selfplayOut = "data/rl_selfplay_gen${gen}.jsonl"
    $candidateCheckpoint = "checkpoints/model_rl_gen${gen}.pt"

    Write-Log "--- gen ${gen}: self-play from $bestCheckpoint ($SelfplayGames games, simulations=$SelfplaySimulations, concurrency=$SelfplayConcurrency, vs-builtin-ratio=$VsBuiltinRatio) ---"
    & $PythonCpu -m yonmoku_nn.rl_selfplay --checkpoint $bestCheckpoint --games $SelfplayGames `
        --simulations $SelfplaySimulations --concurrency $SelfplayConcurrency --out $selfplayOut `
        --vs-builtin-ratio $VsBuiltinRatio --vs-builtin-levels $VsBuiltinLevels
    if ($LASTEXITCODE -ne 0) {
        Write-Log "ERROR: rl_selfplay failed at gen ${gen} (exit $LASTEXITCODE). Aborting."
        exit 1
    }

    Write-Log "--- gen ${gen}: training (GPU, data=$DataGlob, init=$bestCheckpoint, lr=$Lr, epochs=$TrainEpochs) ---"
    & $PythonGpu -m yonmoku_nn.train_rl --data $DataGlob --init-checkpoint $bestCheckpoint --out $candidateCheckpoint `
        --lr $Lr --epochs $TrainEpochs
    if ($LASTEXITCODE -ne 0) {
        Write-Log "ERROR: train_rl failed at gen ${gen} (exit $LASTEXITCODE). Aborting."
        exit 1
    }

    Write-Log "--- gen ${gen}: evaluate candidate (vs $Opponent, $EvalGames games) ---"
    $candidateWinRate = Get-WinRate -Checkpoint $candidateCheckpoint

    if ($candidateWinRate -gt $bestWinRate) {
        Write-Log "gen ${gen} PROMOTED: $candidateWinRate% > previous best $bestWinRate%. New base: $candidateCheckpoint"
        $bestCheckpoint = $candidateCheckpoint
        $bestWinRate = $candidateWinRate
    } elseif ($candidateWinRate -eq $bestWinRate) {
        Write-Log "gen ${gen} TIED: $candidateWinRate% == previous best $bestWinRate%. Keeping $bestCheckpoint as the base for the next attempt (no strict improvement, so not promoted)."
    } else {
        Write-Log "gen ${gen} REJECTED: $candidateWinRate% < previous best $bestWinRate%. Keeping $bestCheckpoint as the base for the next attempt."
    }
}

Write-Log "=== RL loop finished. Best checkpoint: $bestCheckpoint (win rate $bestWinRate% vs $Opponent) ==="
Write-Log "Full log is in this file: $logFile"
